import fs from "node:fs";
import path from "node:path";

/**
 * Real git history for one entry, generated by `generateEntryHistory`
 * (`entry-history-generator.ts`, called from `next.config.ts`) and read
 * back here by `loadEntryHistory`. Nothing here is invented: an entry with
 * no qualifying commits yet (e.g. added but not committed) is
 * `"unavailable"` rather than given fabricated dates.
 */
export type EntryCommit = Readonly<{
  sha: string;
  committedAt: string;
  subject: string;
  body: string;
}>;

export type EntryHistory =
  | Readonly<{
      status: "available";
      createdAt: string;
      updatedAt: string;
      commits: readonly EntryCommit[];
    }>
  | Readonly<{ status: "unavailable"; reason: string }>;

let cachedHistory: Record<string, EntryHistory> | undefined;

/**
 * Reads the history `generateEntryHistory` wrote. Cached for the life of
 * the process: `next.config.ts` regenerates the file once per dev-server
 * start or build, so re-reading per request would only add I/O, not
 * freshness.
 */
export function loadEntryHistory(repoRoot: string = process.cwd()): Record<string, EntryHistory> {
  if (cachedHistory) return cachedHistory;

  const outputPath = path.join(repoRoot, ".generated", "entry-history.json");
  if (!fs.existsSync(outputPath)) {
    throw new Error(
      `Missing generated entry history at "${outputPath}". Run \`pnpm dev\` or \`pnpm build\` once so next.config.ts can generate it.`,
    );
  }

  cachedHistory = JSON.parse(fs.readFileSync(outputPath, "utf8")) as Record<string, EntryHistory>;
  return cachedHistory;
}
